#!/usr/bin/env python3
"""Inline the three webfonts the overlay uses as base64 @font-face rules.

The overlay is rendered by a headless Chromium that must not depend on the
network mid-render, and Chromium refuses file:// subresources anyway, so the
latin subsets get baked straight into fonts.css.
"""

import base64
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

FAMILIES = [
    ("Fraunces", "Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900"),
    ("Inter", "Inter:wght@300..800"),
    ("Outfit", "Outfit:wght@300..700"),
]


def get(url):
    return subprocess.run(
        ["curl", "-sS", "-L", "-A", UA, url],
        capture_output=True, check=True).stdout


def main():
    out = ["/* Generated by fetch_fonts.py -- do not edit. */"]
    for name, spec in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=block").decode()
        # Keep only the latin block: everything else is dead weight in a
        # base64 payload that Chromium has to parse for all 900 frames.
        blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})",
                            css, re.S)
        kept = 0
        for subset, block in blocks:
            if subset != "latin":
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            data = base64.b64encode(get(url)).decode()
            block = re.sub(r"url\(https://[^)]+\.woff2\)",
                           f"url(data:font/woff2;base64,{data})", block)
            block = re.sub(r"\s*unicode-range:[^;]+;", "", block)
            out.append(block)
            kept += 1
        print(f"{name}: {kept} face(s)")

    path = os.path.join(HERE, "fonts.css")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"-> {path} ({os.path.getsize(path) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
